patchedDependencies:
  # Approach to custom icons taken directly from https://github.com/PaperMC/docs
  '@astrojs/starlight': patches/@astrojs__starlight.patch

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.10.4'
  - '@astrojs/markdown-remark@7.2.4'
  - '@astrojs/markdown-satteri@0.3.7'
  - '@astrojs/mdx@7.0.7'
  - astro@7.2.4 || 7.2.8
  - '@img/sharp-darwin-arm64@0.35.4'
  - '@img/sharp-darwin-x64@0.35.4'
  - '@img/sharp-freebsd-wasm32@0.35.4'
  - '@img/sharp-libvips-darwin-arm64@1.3.3'
  - '@img/sharp-libvips-darwin-x64@1.3.3'
  - '@img/sharp-libvips-linux-arm64@1.3.3'
  - '@img/sharp-libvips-linux-arm@1.3.3'
  - '@img/sharp-libvips-linux-ppc64@1.3.3'
  - '@img/sharp-libvips-linux-riscv64@1.3.3'
  - '@img/sharp-libvips-linux-s390x@1.3.3'
  - '@img/sharp-libvips-linux-x64@1.3.3'
  - '@img/sharp-libvips-linuxmusl-arm64@1.3.3'
  - '@img/sharp-libvips-linuxmusl-x64@1.3.3'
  - '@img/sharp-linux-arm64@0.35.4'
  - '@img/sharp-linux-arm@0.35.4'
  - '@img/sharp-linux-ppc64@0.35.4'
  - '@img/sharp-linux-riscv64@0.35.4'
  - '@img/sharp-linux-s390x@0.35.4'
  - '@img/sharp-linux-x64@0.35.4'
  - '@img/sharp-linuxmusl-arm64@0.35.4'
  - '@img/sharp-linuxmusl-x64@0.35.4'
  - '@img/sharp-wasm32@0.35.4'
  - '@img/sharp-webcontainers-wasm32@0.35.4'
  - '@img/sharp-win32-arm64@0.35.4'
  - '@img/sharp-win32-ia32@0.35.4'
  - '@img/sharp-win32-x64@0.35.4'
  - sharp@0.35.4
